# Generated by Django 5.2.11 on 2026-05-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views_count',
        ),
    ]
