# Generated by Django 5.2.11 on 2026-05-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_categorys_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorys',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.category'),
        ),
    ]
