# Generated by Django 5.2.11 on 2026-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_categorys_alter_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='created',
        ),
    ]
